# Variable

In [1]:
import torch
from torch.autograd import Variable # torch 中 Variable 模块

In [2]:
# 准备鸡蛋
tensor = torch.FloatTensor([[1,2],[3,4]])
# 把鸡蛋放到篮子里, requires_grad是参不参与误差反向传播, 要不要计算梯度
variable = Variable(tensor, requires_grad=True)

print("Tensor:\n" + str(tensor))
print("\n")
print("Variable:\n" + str(variable))

Tensor:
tensor([[1., 2.],
        [3., 4.]])


Variable:
tensor([[1., 2.],
        [3., 4.]], requires_grad=True)


# Variable 计算, 梯度

In [3]:
t_out = torch.mean(tensor*tensor)       # x^2
v_out = torch.mean(variable*variable)   # x^2
print(t_out)
print(v_out) 

tensor(7.5000)
tensor(7.5000, grad_fn=<MeanBackward0>)


到目前为止, 我们看不出什么不同, 但是时刻记住, Variable 计算时, 它在背景幕布后面一步步默默地搭建着一个庞大的系统, 叫做计算图, computational graph. 这个图是用来干嘛的? 原来是将所有的计算步骤 (节点) 都连接起来, 最后进行误差反向传递的时候, 一次性将所有 variable 里面的修改幅度 (梯度) 都计算出来, 而 tensor 就没有这个能力啦.

v_out = torch.mean(variable*variable) 就是在计算图中添加的一个计算步骤, 计算误差反向传递的时候有他一份功劳, 我们就来举个例子:

In [4]:
v_out.backward()    # 模拟 v_out 的误差反向传递

# v_out = torch.mean(variable*variable) 这是定义
# v_out = 1/4 * sum(variable*variable) 这是计算图中的 v_out的实际数学公式
# 针对于 v_out 的梯度就是：
# d(v_out)/d(variable) = 1/4*2*variable = variable/2
print("variable.grad:\n")
print(variable.grad)    # 初始 Variable 的梯度

variable.grad:

tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])


# 获取 Variable 里面的数据

直接print(variable)只会输出 Variable 形式的数据, 在很多时候是用不了的(比如想要用 plt 画图), 所以我们要转换一下, 将它变成 tensor 形式.

In [5]:
print(variable)     #  Variable 形式


print(variable.data)    # tensor 形式


print(variable.data.numpy())    # numpy 形式

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)
tensor([[1., 2.],
        [3., 4.]])
[[1. 2.]
 [3. 4.]]
